<a href="https://colab.research.google.com/github/sebastiaansnel/the_cost_of_k_anonimity/blob/main/Thesis_preprocessing_csv_files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data",
                 names = ["ID number", "Diagnosis", "Radius", "Texture", "Perimetert", "Area", "Smoothness", "Compactness", "Concavity","Concave point", "Symmetry", "Fractal dimension", "unknown1", "unknown2", "unknown3", "unknown4", "unknown5", "unknown6", "unknown7", "unknown8", "unknown9", "unknown10", "unknown11", "unknown12", "unknown13", "unknown14", "unknown15", "unknown16", "unknown17", "unknown18", "unknown19", "unknown20"], decimal=",")

In [ ]:
df1.head()

,ID number,Diagnosis,Radius,Texture,Perimetert,Area,Smoothness,Compactness,Concavity,Concave point,...,unknown11,unknown12,unknown13,unknown14,unknown15,unknown16,unknown17,unknown18,unknown19,unknown20
0,842302,M,17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,...,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189
1,842517,M,20.57,17.77,132.9,1326,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.8,1956,0.1238,0.1866,0.2416,0.186,0.275,0.08902
2,84300903,M,19.69,21.25,130,1203,0.1096,0.1599,0.1974,0.1279,...,23.57,25.53,152.5,1709,0.1444,0.4245,0.4504,0.243,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.1425,0.2839,0.2414,0.1052,...,14.91,26.5,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.173
4,84358402,M,20.29,14.34,135.1,1297,0.1003,0.1328,0.198,0.1043,...,22.54,16.67,152.2,1575,0.1374,0.205,0.4,0.1625,0.2364,0.07678

In [ ]:
df1.to_csv("wdbc", index=False)

In [ ]:
df2 = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/voting-records/house-votes-84.data",
                 names = ["Class name", "Handicapped infants", "Water project cost sharing", "Adoption of budget resolution", "Physician-free-freeze ", "El-salvador-aid", "religious-groups-in-schools", "anti-satellite-test-ban", "aid-to-nicaraguan-contras","mx-missile", "immigration", "synfuels-corporation-cutback", "education-spending", "superfund-right-to-sue", "crime", "duty-free-exports", "export-administration-act-south-africa"])
df2.head()

,Class name,Handicapped infants,Water project cost sharing,Adoption of budget resolution,Physician-free-freeze,El-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,republican,n,y,n,y,y,y,n,n,n,y,?,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,?
2,democrat,?,y,y,?,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,?,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,?,y,y,y,y

In [ ]:
df2.to_csv("Congressional-voting-records", index=False)

In [ ]:


df3 = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data-original",
                 names = ["mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model year", "origin", "car name"])
df3.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0 8. 307.0 130.0 3504. 1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,15.0 8. 350.0 165.0 3693. 1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,18.0 8. 318.0 150.0 3436. 1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16.0 8. 304.0 150.0 3433. 1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,17.0 8. 302.0 140.0 3449. 1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN